### ISSUE TITLE
Option to hide prices from menu

### ISSUE THREAD

**Issue by zeekaran** [karlomikus/vue-salt-rim#186] opened 2024-07-15 23:41 UTC
The menu feature should have an option to hide prices. I could be wrong, but I think most users here are amateur / home bartenders. Just a simple checkbox, would suffice (per drink or for the whole menu). Alternatively, "0.00" or "null"/empty string (which is currently not allowed and defaults to 0.00) could just not display.

**Comment by reefland** [comment] 2024-08-03 17:36
oops. I made a duplicate of this <https://github.com/karlomikus/bar-assistant/issues/308>

**Comment by karlomikus** [comment] 2024-08-05 20:39
Live in [v2.17.0](https://github.com/karlomikus/vue-salt-rim/releases/tag/v2.17.0)

**Closed by karlomikus** 2024-08-05 20:39 UTC
Labels: feat

**Comment by reefland** [comment] 2024-08-06 02:52
Looks good, thanks!
